---
- name: Install Nginx on servers
  hosts: all
  become: true  


  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian" 

    - name: Ensure Nginx is running
      service:
        name: nginx
        state: started
        enabled: true
