
pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                cleanWs()
                git branch: 'main', url: 'https://github.com/user/repo.git'
            }
        }
        stage('Build') {
            steps {
                sh './gradlew build' // Зависит от вашего сборщика (Maven, Gradle, NPM и т. д.)
            }
        }
        stage('Test') {
            steps {
                sh './gradlew test' // Команда запуска тестов
            }
        }
    }
    post {
        success {
            echo 'Build successful'
        }
        failure {
            echo 'Build failed'
        }
    }
}
